# Generated by Django 2.1.4 on 2019-04-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('isbn_id', models.IntegerField()),
                ('b_type', models.CharField(max_length=64)),
                ('img_path', models.TextField(max_length=3000)),
                ('name', models.CharField(max_length=64)),
                ('publisher', models.TextField(max_length=1000)),
                ('auther', models.TextField(max_length=1000)),
                ('price', models.FloatField()),
                ('number', models.IntegerField(default=2)),
                ('can_lend', models.IntegerField(default=2)),
                ('descri', models.CharField(default='暂无', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='BookAdmin',
            fields=[
                ('baid', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BookState',
            fields=[
                ('bsid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('lend_time', models.DateTimeField(auto_now_add=True)),
                ('should_back_time', models.IntegerField(default=168)),
                ('back_time', models.DateTimeField(null=True)),
                ('down', models.IntegerField(verbose_name=0)),
                ('beizhu', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DB_user',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('student_id', models.IntegerField()),
                ('card_id', models.IntegerField()),
                ('lend_num', models.IntegerField(default=3)),
                ('junshi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('can_lend', models.IntegerField()),
                ('add_user', models.IntegerField()),
                ('delete_self', models.IntegerField()),
                ('delete_user', models.IntegerField()),
                ('add_book', models.IntegerField()),
                ('delete_book', models.IntegerField()),
                ('update_book', models.IntegerField()),
                ('query_book', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeToBook',
            fields=[
                ('btid', models.AutoField(primary_key=True, serialize=False)),
                ('bid', models.IntegerField()),
                ('tid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserToBook',
            fields=[
                ('ubid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('bid', models.IntegerField()),
                ('bsid', models.IntegerField()),
            ],
        ),
    ]
