# Generated by Django 2.1.4 on 2019-04-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_user',
            name='card_id',
        ),
    ]
