# Generated by Django 2.1.4 on 2019-02-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('u_ans', models.TextField(max_length=2000)),
                ('a_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('q_name', models.CharField(max_length=80)),
                ('q_des', models.CharField(max_length=400)),
                ('q_que', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('family_type', models.IntegerField(default=0)),
                ('address_type', models.IntegerField(default=0)),
                ('marry_type', models.IntegerField(default=0)),
                ('is_full', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart_test.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heart_test.User'),
        ),
    ]
