# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SERVERS.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(985, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 271, 541))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(100, 20, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(160, 20, 54, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(220, 20, 54, 12))
        self.label_4.setObjectName("label_4")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 251, 491))
        self.listWidget.setObjectName("listWidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 10, 461, 541))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 500, 341, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(370, 500, 81, 31))
        self.pushButton.setObjectName("pushButton")
        self.msg_list = QtWidgets.QListWidget(self.groupBox_2)
        self.msg_list.setGeometry(QtCore.QRect(10, 20, 441, 471))
        self.msg_list.setObjectName("msg_list")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(770, 100, 191, 451))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 54, 12))
        self.label_5.setObjectName("label_5")
        self.room_list = QtWidgets.QListWidget(self.groupBox_3)
        self.room_list.setGeometry(QtCore.QRect(10, 40, 171, 401))
        self.room_list.setObjectName("room_list")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 570, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.state = QtWidgets.QLabel(self.centralwidget)
        self.state.setGeometry(QtCore.QRect(150, 570, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.state.setFont(font)
        self.state.setText("")
        self.state.setObjectName("state")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(290, 570, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.address = QtWidgets.QLabel(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(430, 570, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.address.setFont(font)
        self.address.setText("")
        self.address.setObjectName("address")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(570, 570, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.port = QtWidgets.QLabel(self.centralwidget)
        self.port.setGeometry(QtCore.QRect(680, 570, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.port.setFont(font)
        self.port.setText("")
        self.port.setObjectName("port")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(770, 10, 191, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.room_id = QtWidgets.QLineEdit(self.groupBox_4)
        self.room_id.setGeometry(QtCore.QRect(10, 20, 171, 21))
        self.room_id.setObjectName("room_id")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 50, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Servers"))
        self.groupBox.setTitle(_translate("MainWindow", "player_list"))
        self.label.setText(_translate("MainWindow", "player"))
        self.label_2.setText(_translate("MainWindow", "player_id"))
        self.label_3.setText(_translate("MainWindow", "in_where"))
        self.label_4.setText(_translate("MainWindow", "state"))
        self.groupBox_2.setTitle(_translate("MainWindow", "msg"))
        self.pushButton.setText(_translate("MainWindow", "command"))
        self.groupBox_3.setTitle(_translate("MainWindow", "room"))
        self.label_5.setText(_translate("MainWindow", "room_id"))
        self.label_7.setText(_translate("MainWindow", "server stauts:"))
        self.label_8.setText(_translate("MainWindow", "server address:"))
        self.label_9.setText(_translate("MainWindow", "server port:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "creat_room"))
        self.pushButton_2.setText(_translate("MainWindow", "creat"))

