# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_m.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 211, 631))
        self.groupBox.setObjectName("groupBox")
        self.room_list_view = QtWidgets.QListWidget(self.groupBox)
        self.room_list_view.setGeometry(QtCore.QRect(10, 20, 191, 601))
        self.room_list_view.setObjectName("room_list_view")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 70, 691, 631))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(930, 70, 181, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.current_room_list = QtWidgets.QListWidget(self.groupBox_3)
        self.current_room_list.setGeometry(QtCore.QRect(10, 20, 161, 121))
        self.current_room_list.setObjectName("current_room_list")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(930, 230, 181, 341))
        self.groupBox_4.setObjectName("groupBox_4")
        self.msg_list = QtWidgets.QListWidget(self.groupBox_4)
        self.msg_list.setGeometry(QtCore.QRect(10, 20, 161, 311))
        self.msg_list.setObjectName("msg_list")
        self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(980, 630, 91, 31))
        self.exit_btn.setObjectName("exit_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.user_name = QtWidgets.QLabel(self.centralwidget)
        self.user_name.setGeometry(QtCore.QRect(490, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.user_name.setFont(font)
        self.user_name.setText("")
        self.user_name.setAlignment(QtCore.Qt.AlignCenter)
        self.user_name.setObjectName("user_name")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(760, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.room_name = QtWidgets.QLabel(self.centralwidget)
        self.room_name.setGeometry(QtCore.QRect(930, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.room_name.setFont(font)
        self.room_name.setText("")
        self.room_name.setObjectName("room_name")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(980, 630, 91, 31))
        self.login_btn.setObjectName("login_btn")
        self.restart_btn = QtWidgets.QPushButton(self.centralwidget)
        self.restart_btn.setGeometry(QtCore.QRect(980, 680, 91, 31))
        self.restart_btn.setObjectName("restart_btn")
        self.ready_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ready_btn.setGeometry(QtCore.QRect(980, 680, 91, 31))
        self.ready_btn.setObjectName("ready_btn")
        self.invite_btn = QtWidgets.QPushButton(self.centralwidget)
        self.invite_btn.setGeometry(QtCore.QRect(980, 590, 91, 31))
        self.invite_btn.setObjectName("invite_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "wuzi_game"))
        self.groupBox.setTitle(_translate("MainWindow", "room_list"))
        self.groupBox_2.setTitle(_translate("MainWindow", "current_game"))
        self.groupBox_3.setTitle(_translate("MainWindow", "room_people"))
        self.groupBox_4.setTitle(_translate("MainWindow", "message"))
        self.exit_btn.setText(_translate("MainWindow", "exit"))
        self.label.setText(_translate("MainWindow", "welcome to our wuzi_game!"))
        self.label_3.setText(_translate("MainWindow", "NOW you in ROOM:"))
        self.login_btn.setText(_translate("MainWindow", "LOGIN"))
        self.restart_btn.setText(_translate("MainWindow", "restart"))
        self.ready_btn.setText(_translate("MainWindow", "ready"))
        self.invite_btn.setText(_translate("MainWindow", "invite"))

